name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      #- name: Set up Python
        #uses: actions/setup-python@v4
         #with:
          #python-version: '3.9.11'  # Use Python 3.9.11

      #- name: Display Python version
        #run: python --version

      - name: Display working directory
        run: pwd

      - name: List files in the directory
        run: ls -la

      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip3 install -r requirements.txt

      - name: Run Flask application
        run: |
          source venv/bin/activate
          gunicorn --bind 0.0.0.0:5004 app:app
